import { Hotel, City } from './types';

export const cities: City[] = [
  {
    id: '1',
    name: 'Đà Nẵng',
    slug: 'da-nang',
    race_name: 'Manulife Danang International Marathon',
    race_date: '2026-08-15',
  },
  {
    id: '2',
    name: 'Hà Nội',
    slug: 'ha-noi',
    race_name: 'VnExpress Marathon Hanoi Midnight',
    race_date: '2026-11-20',
  },
  {
    id: '3',
    name: 'Hồ Chí Minh',
    slug: 'ho-chi-minh',
    race_name: 'Techcombank Ho Chi Minh City International Marathon',
    race_date: '2026-12-05',
  },
];

export const hotels: Hotel[] = [
  {
    id: 'h1',
    hotel_name: 'Mường Thanh Luxury Đà Nẵng',
    slug: 'muong-thanh-luxury',
    city: 'da-nang',
    stars: 5,
    address: '270 Võ Nguyên Giáp, Đà Nẵng',
    distance_to_race: 0.3,
    price_range: 'luxury',
    price_display: '1.800.000 - 2.500.000 VNĐ',
    rating_location: 5,
    rating_price: 4,
    rating_facility: 5,
    rating_runner: 5,
    highlights: [
      'Ăn sáng sớm từ 3:00 AM',
      'Check-out muộn tới 2:00 PM',
      'Có bồn tắm ngâm chân thư giãn',
    ],
    pros: [
      'Vị trí cực gần vạch xuất phát (3 phút đi bộ)',
      'Phòng rộng, view biển đẹp',
      'Dịch vụ chuyên nghiệp cho runner',
    ],
    cons: [
      'Giá cao vào mùa giải',
      'Thang máy hơi chậm lúc cao điểm',
    ],
    early_breakfast: true,
    late_checkout: true,
    luggage_storage: true,
    runner_friendly: true,
    best_for: ['Gia đình', 'Người nghỉ dưỡng', 'Nhóm bạn'],
    booking_url: 'https://booking.com/example-1',
    image_url: 'https://picsum.photos/seed/hotel1/800/600',
    description: 'Khách sạn 5 sao tiêu chuẩn quốc tế, nằm ngay sát bãi biển Mỹ Khê và chỉ cách vạch xuất phát giải chạy vài bước chân. Đây là lựa chọn hàng đầu cho các runner muốn tối ưu thời gian nghỉ ngơi.',
  },
  {
    id: 'h2',
    hotel_name: 'Sala Danang Beach Hotel',
    slug: 'sala-danang-beach',
    city: 'da-nang',
    stars: 4,
    address: '36-38 Lâm Hoành, Đà Nẵng',
    distance_to_race: 0.8,
    price_range: 'mid',
    price_display: '1.200.000 - 1.600.000 VNĐ',
    rating_location: 4,
    rating_price: 5,
    rating_facility: 4,
    rating_runner: 4,
    highlights: [
      'Hỗ trợ giữ đồ sau khi check-out',
      'Bể bơi vô cực ngắm biển',
      'Gần nhiều quán ăn ngon',
    ],
    pros: [
      'Giá cả hợp lý so với chất lượng',
      'Phòng thiết kế hiện đại, sạch sẽ',
      'Nhân viên thân thiện',
    ],
    cons: [
      'Hơi xa vạch xuất phát hơn một chút',
      'Khu vực xung quanh hơi ồn ào',
    ],
    early_breakfast: true,
    late_checkout: false,
    luggage_storage: true,
    runner_friendly: true,
    best_for: ['Solo runner', 'Nhóm bạn', 'Người tiết kiệm'],
    booking_url: 'https://booking.com/example-2',
    image_url: 'https://picsum.photos/seed/hotel2/800/600',
    description: 'Khách sạn 4 sao hiện đại với tầm nhìn tuyệt đẹp ra biển. Dù cách vạch xuất phát khoảng 800m, nhưng đây vẫn là lựa chọn tuyệt vời nhờ giá cả cạnh tranh và dịch vụ tốt.',
  },
  {
    id: 'h3',
    hotel_name: 'Haian Beach Hotel & Spa',
    slug: 'haian-beach-hotel',
    city: 'da-nang',
    stars: 4,
    address: '278 Võ Nguyên Giáp, Đà Nẵng',
    distance_to_race: 0.4,
    price_range: 'mid',
    price_display: '1.400.000 - 1.900.000 VNĐ',
    rating_location: 5,
    rating_price: 4,
    rating_facility: 4,
    rating_runner: 4,
    highlights: [
      'Vị trí đắc địa',
      'Có spa massage chân',
      'Buffet sáng đa dạng',
    ],
    pros: [
      'Rất gần vạch xuất phát',
      'Dịch vụ spa tốt cho phục hồi',
    ],
    cons: [
      'Phòng hơi nhỏ',
    ],
    early_breakfast: false,
    late_checkout: true,
    luggage_storage: true,
    runner_friendly: true,
    best_for: ['Solo runner', 'Nhóm bạn'],
    booking_url: 'https://booking.com/example-3',
    image_url: 'https://picsum.photos/seed/hotel3/800/600',
    description: 'Nằm ngay cạnh Mường Thanh, Haian mang đến trải nghiệm trẻ trung hơn với dịch vụ spa chuyên nghiệp, rất phù hợp để runner thư giãn sau cuộc đua.',
  },
];
